spring:
  application:
    name: EventConsumerService
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: event-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.abarigena.eventconsumerservice.dto.DomainEvent
        spring.json.use.type.headers: false
    listener:
      ack-mode: MANUAL_IMMEDIATE


app:
  kafka:
    topics:
      taskflow-dlq: taskflow.dlq
      taskflow-events: taskflow.events

logging:
  level:
    com.abarigena.eventconsumerservice: INFO
    org.springframework.kafka: INFO
    root: WARN



server:
  port: 8081