server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: taskflowdb
      username: mongodb
      password: mongodb
      # authentication-database: admin # Relying on Spring Boot's default behavior.
                                    # MONGO_INITDB_DATABASE ('taskflowdb') is where the user 'mongodb' is created.
                                    # Spring Boot should try to authenticate against this database.
                                    # If issues, it might need to be explicitly set to 'taskflowdb' or 'admin'.
